stages:
  - test
  - deploy

.test-python: &test-python
  stage: test
  image: python

  script:
    - python -m pip install .
    - python -m pip install -r requirements_doc.txt
    - python -c "import slurmpter"
    - python -c "from slurmpter import Slurm"
    - python -c "from slurmpter import SlurmJob"
    - python -c "from slurmpter import Dagman"
    - python -c "from slurmpter import DagmanJob"

basic-3.5:
    <<: *test-python

python-3.5:
    stage: test
    image: continuumio/miniconda3:latest
    before_script:
        - conda install anaconda-client -n base
        - conda create -n slurmpter-test python=3.5
        - conda init slurmpter-test
        - conda activate slurmpter-test
    script:
        - conda install -c anaconda graphviz
        - python -m pip install -U pytest-cov
        - python -m pip install -U coverage-badge
        - python -m pip install -U flake8
        - python -m pip install -U sphinx
        - python -m pip install -r requirements_doc.txt
        - python -m pip install .
        - flake8 .
        - pytest --cov=slurmpter --durations 10
        - coverage html
        - coverage-badge -o coverage_badge.svg -f
        - cd docs
        - make clean
        - make html

    artifacts:
        paths:
            - htmlcov/
            - coverage_badge.svg
            - docs/_build/html/


