stages:
  - test
  - deploy

.test-python: &test-python
  stage: test
  image: python

  script:
    - python -m pip install .
    - python -c "import slurmpter"
    - python -c "from slurmpter import Slurm"
    - python -c "from slurmpter import SlurmJob"
    - python -c "from slurmpter import Dagman"
    - python -c "from slurmpter import DagmanJob"

python-3.5:
    <<: *test-python
    image: python:3.5
